name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  msys2-clangarm64:
    runs-on: windows-11-arm
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: git unzip
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
      - name: Prepare version file
        run: echo $GITHUB_SHA > version
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v4.0.3-stable
          artifacts: "node.tar.gz"
